apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: release-triage-k8s-io
  namespace: triageparty-release
  annotations:
    acme.cert-manager.io/http01-override-ingress-name: "triage-party-release"
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: release-triage-k8s-io-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - release.triage.k8s.io
