# google group for gcr.io/k8s-staging-external-dns is k8s-infra-staging-external-dns@kubernetes.io
registries:
- name: gcr.io/k8s-staging-external-dns
  src: true
- name: us.gcr.io/k8s-artifacts-prod/external-dns
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod/external-dns
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod/external-dns
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
imagesPath: "../../images/k8s-staging-external-dns/images.yaml"
