apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: perfdash-k8s-io
  annotations:
    acme.cert-manager.io/http01-override-ingress-name: "perfdash"
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: perfdash-k8s-io-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - perf-dash.k8s.io
