# Configuration for the kubernetes.io Google Groups setup

# file path of the google groups service account token
token-file: k8s-gsuite-1781c2662b57.json

# Email id of the bot service account
bot-id: wg-k8s-infra-api@kubernetes.io

# Configuration file for the groups/members information
groups-file: groups.yaml
