# Configuration for the kubernetes.io Google Groups setup

# Secret version of the service account key to use
secret-version: projects/k8s-gsuite/secrets/gsuite-groups-manager_key/versions/latest

# Email id of the bot service account
bot-id: wg-k8s-infra-api@kubernetes.io
