# google group for gcr.io/k8s-staging-etcd is k8s-infra-staging-etcd@kubernetes.io
registries:
- name: gcr.io/k8s-staging-etcd
  src: true
- name: us.gcr.io/k8s-artifacts-prod/etcd
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod/etcd
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod/etcd
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
