apiVersion: v1
data:
  config: |
    resources:
    - names:
      - k8s-infra-e2e-boskos-001
      - k8s-infra-e2e-boskos-002
      - k8s-infra-e2e-boskos-003
      - k8s-infra-e2e-boskos-004
      - k8s-infra-e2e-boskos-005
      - k8s-infra-e2e-boskos-006
      - k8s-infra-e2e-boskos-007
      - k8s-infra-e2e-boskos-008
      - k8s-infra-e2e-boskos-009
      - k8s-infra-e2e-boskos-010
      - k8s-infra-e2e-boskos-011
      - k8s-infra-e2e-boskos-012
      - k8s-infra-e2e-boskos-013
      - k8s-infra-e2e-boskos-014
      - k8s-infra-e2e-boskos-015
      - k8s-infra-e2e-boskos-016
      - k8s-infra-e2e-boskos-017
      - k8s-infra-e2e-boskos-018
      - k8s-infra-e2e-boskos-019
      - k8s-infra-e2e-boskos-020
      - k8s-infra-e2e-boskos-021
      - k8s-infra-e2e-boskos-022
      - k8s-infra-e2e-boskos-023
      - k8s-infra-e2e-boskos-024
      - k8s-infra-e2e-boskos-025
      - k8s-infra-e2e-boskos-026
      - k8s-infra-e2e-boskos-027
      - k8s-infra-e2e-boskos-028
      - k8s-infra-e2e-boskos-029
      - k8s-infra-e2e-boskos-030
      - k8s-infra-e2e-boskos-031
      - k8s-infra-e2e-boskos-032
      - k8s-infra-e2e-boskos-033
      - k8s-infra-e2e-boskos-034
      - k8s-infra-e2e-boskos-035
      - k8s-infra-e2e-boskos-036
      - k8s-infra-e2e-boskos-037
      - k8s-infra-e2e-boskos-038
      - k8s-infra-e2e-boskos-039
      - k8s-infra-e2e-boskos-040
      - k8s-infra-e2e-boskos-041
      - k8s-infra-e2e-boskos-042
      - k8s-infra-e2e-boskos-043
      - k8s-infra-e2e-boskos-044
      - k8s-infra-e2e-boskos-045
      - k8s-infra-e2e-boskos-046
      - k8s-infra-e2e-boskos-047
      - k8s-infra-e2e-boskos-048
      - k8s-infra-e2e-boskos-049
      - k8s-infra-e2e-boskos-050
      - k8s-infra-e2e-boskos-051
      - k8s-infra-e2e-boskos-052
      - k8s-infra-e2e-boskos-053
      - k8s-infra-e2e-boskos-054
      - k8s-infra-e2e-boskos-055
      - k8s-infra-e2e-boskos-056
      - k8s-infra-e2e-boskos-057
      - k8s-infra-e2e-boskos-058
      - k8s-infra-e2e-boskos-059
      - k8s-infra-e2e-boskos-060
      - k8s-infra-e2e-boskos-061
      - k8s-infra-e2e-boskos-062
      - k8s-infra-e2e-boskos-063
      - k8s-infra-e2e-boskos-064
      - k8s-infra-e2e-boskos-065
      - k8s-infra-e2e-boskos-066
      - k8s-infra-e2e-boskos-067
      - k8s-infra-e2e-boskos-068
      - k8s-infra-e2e-boskos-069
      - k8s-infra-e2e-boskos-070
      - k8s-infra-e2e-boskos-071
      - k8s-infra-e2e-boskos-072
      - k8s-infra-e2e-boskos-073
      - k8s-infra-e2e-boskos-074
      - k8s-infra-e2e-boskos-075
      - k8s-infra-e2e-boskos-076
      - k8s-infra-e2e-boskos-077
      - k8s-infra-e2e-boskos-078
      - k8s-infra-e2e-boskos-079
      - k8s-infra-e2e-boskos-080
      state: dirty
      type: gce-project
    - names:
      - k8s-infra-e2e-boskos-scale-01
      - k8s-infra-e2e-boskos-scale-02
      - k8s-infra-e2e-boskos-scale-03
      - k8s-infra-e2e-boskos-scale-04
      - k8s-infra-e2e-boskos-scale-05
      state: dirty
      type: scalability-project
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: resources
  namespace: test-pods
