apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gcsweb-k8s-io
  namespace: gcsweb
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: gcsweb-k8s-io-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: gcsweb.k8s.io
  dnsNames:
  - gcsweb.k8s.io
  - gcsweb.kubernetes.io
