apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: k8s-infra-team-private+letsencrypt@kubernetes.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letencrypt-staging-account-key
    # Enable the HTTP01 challenge mechanism for this Issuer
    http01: {}
