apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: k8s-infra-team-private+letsencrypt@googlegroups.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letencrypt-prod-account-key
    # Enable the HTTP01 challenge mechanism for this Issuer
    http01: {}
